language:
  - python


python:
  -"3.4"

install:
  -pip install coverage
  -pip install coveralls   #install python-coveralls
  -pip install pytest-cov
  -pip install -r requirements.txt

script:
  -pytest --cov tests/test_app.py

after_success:
  -coverage report
  -coveralls    #uploads reports to  coveralls.io
